syntax = "proto3";

package nest.app;

import "common.proto";

service UsersService {
    rpc CreateUser (CreateUserRequest) returns (UserResponse) {}
    rpc FindAllUsers (FindAllUsersRequest) returns (UsersResponse) {}
    rpc FindOneUser (FindOneRequest) returns (UserResponse) {}
    rpc UpdateUser (UpdateUserRequest) returns (UserResponse) {}
    rpc RemoveUser (FindOneRequest) returns (UserResponse) {}
    rpc QueryUsers (stream PaginationDto) returns (stream UsersResponse) {}
}

message CreateUserRequest {
    string email = 1;
    string password = 2;
}

message FindAllUsersRequest {
    int32 page = 1;
    int32 limit = 2;
}

message UpdateUserRequest {
    string id = 1;
    string email = 2;
    bool isActive = 3;
    bool isVerified = 4;
}

message UsersResponse {
    repeated UserResponse users = 1;
    int32 total = 2;
    int32 page = 3;
    int32 limit = 4;
}

message UserResponse {
    string id = 1;
    string email = 2;
    bool isActive = 3;
    bool isVerified = 4;
    string createdAt = 5;
    string updatedAt = 6;
}
