name: nest-fastify

services:
  api:
    container_name: api
    build:
      context: ..
      dockerfile: server/Dockerfile
      target: prod
    command: sh -c "yarn build api s&& node dist/apps/api/main"
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - local
    env_file:
      - ../server/.env.prod
    volumes:
      - ../server/apps/api/.env.prod:/app/apps/api/.env.app
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  auth:
    container_name: auth
    build:
      context: ..
      dockerfile: server/Dockerfile
      target: prod
    command: sh -c "yarn build auth && node dist/apps/auth/main"
    restart: unless-stopped
    ports:
      - 8001:8001
    networks:
      - local
    env_file:
      - ../server/.env.prod
    volumes:
      - ../server/apps/auth/.env.prod:/app/apps/auth/.env.app
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  alert:
    container_name: alert
    build:
      context: ..
      dockerfile: server/Dockerfile
      target: prod
    command: sh -c "yarn build alert s&& node dist/apps/alert/main"
    restart: unless-stopped
    ports:
      - 8002:8002
    networks:
      - local
    env_file:
      - ../server/.env.prod
    volumes:
      - ../server/apps/alert/.env.prod:/app/apps/alert/.env.app
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  things-board:
    container_name: things-board
    build:
      context: ..
      dockerfile: server/Dockerfile
      target: prod
    command: sh -c "yarn build things-board s&& node dist/apps/things-board/main"
    restart: unless-stopped
    ports:
      - 8003:8003
    networks:
      - local
    env_file:
      - ../server/.env.prod
    volumes:
      - ../server/apps/things-board/.env.prod:/app/apps/things-board/.env.app
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  postgres:      
    container_name: postgres
    image: postgres:16.4-alpine
    restart: unless-stopped
    ports:  
      - 5432:5432
    networks:
      - local
    env_file:
      - ../server/.env.prod
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - local
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    env_file:
      - ../server/.env.prod
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
  local:

volumes:
  postgres-data:
  rabbitmq-data:
